apiVersion: v1
kind: ConfigMap
metadata:
  name: ma-devops-config
  namespace: ma-devops
  labels:
    app.kubernetes.io/part-of: ma-devops-suite
data:
  PORT: "8080"
  NODE_ENV: "production"
  DB_HOST: "ma-devops-mysql-svc"
  DB_PORT: "3306"
  DB_NAME: "ma_devops_db"
  DB_CONNECTION_LIMIT: "10"
  VITE_API_URL: "/api/v1"
