apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ma-devops-mysql-pvc
  namespace: ma-devops
  labels:
    app: ma-devops-mysql
    app.kubernetes.io/part-of: ma-devops-suite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
