apiVersion: v1
kind: Secret
metadata:
  name: ma-devops-secrets
  namespace: ma-devops
  labels:
    app.kubernetes.io/part-of: ma-devops-suite
type: Opaque
stringData:
  DB_USER: "devops_user"
  DB_PASSWORD: "devops_password"
  MYSQL_ROOT_PASSWORD: "devops_password"
  MYSQL_USER: "devops_user"
  MYSQL_PASSWORD: "devops_password"
  MYSQL_DATABASE: "ma_devops_db"
